### ISSUE TITLE
Lockfile hashing

### ISSUE THREAD

**Issue by JasonGore** [microsoft/backfill#263]
I was exploring how to add yarn's lockfile to the environment glob hash in our repo when I discovered rush's lockfile was not already present. After talking with @kenotron he mentioned that lockfile hashing causes issues and therefore is not included in the environment glob. 

Beyond my yarn/rush hybrid scenario, I'm curious if there are other situations that could cause problems here. If a leaf package changes an internal dep that ends up changing a core dep used by a lot of packages due to yarn's hoisting algorithm, could this cause issues by not having the yarn.lock as part of the environment hash? It seems like this is a case where all packages using that dep should be rebuilt, but only the leaf package would be.

I'm creating this issue because some key stakeholders are gone but I want to make sure this doesn't slip through the cracks.

**Comment by bweggersen** [comment]
Thanks for your report! Backfill resolves every transitive dependency for a given workspace package using the lock file (supporting both yarn lock and pnpm lock files, parsed through workspace-tools). If any package changes its dependencies (either external dependencies (pulled down from the feed) or workspace packages (from the mono repo)), any dependent workspace package will have a new hash representation of its dependencies. If yarn hoists dependencies in node_modules in a way that fails to satisfy the contract defined in yarn.lock, for instance, then that is a case that would not be picked up by backfill. But, hashing the lock file wouldn't help either, so that's probably not relevant. In large monorepos, the lock files update quite often, so in order to have cache which is not invalidated multiple times a day, we need to traverse the dependency chain and do look-up in the parsed lock files to determine all the exact dependencies for each package's dependency tree. Does that answer your concerns?

**Comment by JasonGore** [comment]
I was concerned only about scenarios that do satisfy the yarn.lock contract, but it sounds like the scenarios I was concerned about are already handled. Here are a few examples I was concerned about while migrating to yarn:
1) Deduping dependencies in yarn lock using `yarn-deduplicate` to fix duplicate bundling errors.
2) Updating a dep of a hoisted dep causes the hoisted dep version to be bumped by all packages using it.

But it sounds like based on your reply that backfill should handle these scenarios and rebuild the packages whose deps have changed. If that's true, then my concerns in creating the issue should be addressed.

**Comment by bweggersen** [comment]
Great! Thanks for taking the time to discuss this important point!
